name: Run Robot Framework Tests and Send Email

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  run_tests_and_send_email:
    name: Run Robot Framework Tests and Send Email
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python and pip
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          pip-version: latest

      - name: Install dependencies
        run: |
          pip install robotframework
          pip install robotframework-requests
          pip install robotframework-seleniumlibrary
          pip install rpaframework

      - name: Run Robot Framework tests
        run: |
          robot Admin/Test\ Cases/Scheduled\ Flow/createScheduled.robot

      - name: Upload Log File
        id: upload-log-file
        uses: actions/upload-artifact@v2
        with:
          name: log-file
          path: /home/runner/work/RF-Automation-Test/RF-Automation-Test/log.html

      - name: Upload Log File to GitHub
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.TOKEN_GITHUB }}
          script: |
            const fs = require('fs');
            const path = require('path');
      
            // Ruta del archivo log.html
            const filePath = '/home/runner/work/RF-Automation-Test/RF-Automation-Test/log.html';
      
            // Lee el contenido del archivo
            const fileContent = fs.readFileSync(filePath, 'utf8');
      
            // Nombre de la carpeta en tu repositorio de GitHub
            const folderName = 'Admin/Test Cases/Reports';
      
            // Ruta de destino en tu repositorio
            const destinationPath = path.join(folderName, 'log.html');
      
            // Crea la carpeta si no existe
            fs.mkdirSync(path.dirname(destinationPath), { recursive: true });
      
            // Escribe el archivo en la carpeta destino
            fs.writeFileSync(destinationPath, fileContent);

