name: Run Robot Framework Tests and Send Email

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  run_tests_and_send_email:
    name: Run Robot Framework Tests and Send Email
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python and pip
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          pip-version: latest

      - name: Install dependencies
        run: |
          pip install robotframework
          pip install robotframework-requests
          pip install robotframework-seleniumlibrary
          pip install rpaframework

      - name: Run Robot Framework tests
        run: |
          robot Admin/Test\ Cases/Scheduled\ Flow/createScheduled.robot

      - name: Upload Log File
        uses: actions/upload-artifact@v2
        with:
          name: log-file
          path: /home/runner/work/RF-Automation-Test/RF-Automation-Test/log.html

      - name: Send Email with Log File
        run: |
          echo '{
            "personalizations": [
              {
                "to": [
                  {
                    "email": "nico2795@gmail.com"
                  }
                ],
                "subject": "Test Subject"
              }
            ],
            "from": {
              "email": "nicolas@allrideapp.com"
            },
            "content": [
              {
                "type": "text/plain",
                "value": "This is a test email sent from GitHub Actions."
              }
            ],
            "attachments": [
              {
                "content": "$(base64 /home/runner/work/RF-Automation-Test/RF-Automation-Test/log.html)",
                "type": "text/html",
                "filename": "log.html",
                "disposition": "attachment"
              }
            ]
          }' | curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $SENDGRID_API_KEY" -d @- "https://api.sendgrid.com/v3/mail/send"
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
