name: Run Robot Framework Tests

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  run_tests:
    name: Run Robot Framework Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python and pip
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          pip-version: latest

      - name: Install dependencies
        run: |
          pip install robotframework
          pip install robotframework-requests
          pip install robotframework-seleniumlibrary
          pip install rpaframework

      - name: Run Robot Framework tests
        run: |
          robot Admin/Test\ Cases/Scheduled\ Flow/createScheduled.robot

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: robot-framework-reports
          path: |
            /home/runner/work/RF-Automation-Test/RF-Automation-Test/output.xml
            /home/runner/work/RF-Automation-Test/RF-Automation-Test/log.html
            /home/runner/work/RF-Automation-Test/RF-Automation-Test/report.html

      - name: Send log.html via email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.example.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Log File
          body: Attached is the log file.
          to: nico2795@gmail.com
          from: nico.bustamantesolis@gmail.com
          attachments: /home/runner/work/RF-Automation-Test/RF-Automation-Test/log.html
