name: Run Robot Framework Tests and Send Email

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  run_tests_and_send_email:
    name: Run Robot Framework Tests and Send Email
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python and pip
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          pip-version: latest

      - name: Install dependencies
        run: |
          pip install robotframework
          pip install robotframework-requests
          pip install robotframework-seleniumlibrary
          pip install rpaframework

      - name: Run Robot Framework tests
        run: |
          robot Admin/Test\ Cases/Scheduled\ Flow/createScheduled.robot

      - name: Commit Log File
        run: |
          cd /home/runner/work/RF-Automation-Test/RF-Automation-Test
          git config --global user.email nico2795@gmail.com
          git config --global user.name Nico2795
          git add log.html
          git commit -m "Add log file"
        working-directory: ${{ github.workspace }}

      - name: Push Changes
        run: |
          cd /home/runner/work/RF-Automation-Test/RF-Automation-Test
          git push https://github.com/Nico2795/RF-Automation-Test.git HEAD:main
        env:
          MY_ACCESS_TOKEN: ${{ secrets.TOKEN_GITHUB }}
