name: Run Robot Framework Tests

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    name: Run Robot Framework Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python and pip
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          pip-version: latest  # Esto asegurará que pip se actualice a la última versión

      - name: Install dependencies
        run: |
          pip install robotframework
          pip install robotframework-requests  # Instala RequestsLibrary
          pip install robotframework-seleniumlibrary  # Instala SeleniumLibrary
          pip install rpaframework  # Instala RPA.JSON
          # Instala otras dependencias necesarias para tus pruebas

      - name: Run Robot Framework tests
        run: |
          robot Admin/Test\ Cases/Scheduled\ Flow/createScheduled.robot
