name: Run Robot Framework Tests and Send Email

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  run_tests_and_send_email:
    name: Run Robot Framework Tests and Send Email
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python and pip
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          pip-version: latest

      - name: Install dependencies
        run: |
          pip install robotframework
          pip install robotframework-requests
          pip install robotframework-seleniumlibrary
          pip install rpaframework

      - name: Run Robot Framework tests
        run: |
          robot Admin/Test\ Cases/Scheduled\ Flow/createScheduled.robot

      - name: Upload Log File
        id: upload-log-file
        uses: actions/upload-artifact@v2
        with:
          name: log-file
          path: /home/runner/work/RF-Automation-Test/RF-Automation-Test/log.html

      - name: Get artifact path
        id: get-artifact-path
        run: echo "::set-output name=artifact-path::$(find ${{ github.workspace }} -name 'log.html' -print -quit)"

      - name: Move log.html to Reports folder
        run: |
          mkdir -p Admin/Test\ Cases/Reports/
          mv "${{ steps.get-artifact-path.outputs.artifact-path }}" /home/runner/work/RF-Automation-Test/RF-Automation-Test/Admin/Test\ Cases/Reports/

      - name: Send Email with Log File
        uses: licenseware/send-email-notification@v1
        with:
          api-key: ${{ secrets.SENDGRID_API_KEY }}
          subject: Test Subject
          from-email: nicolas@allrideapp.com
          to-email: nico2795@gmail.com
          markdown-body: |
            This is a test email sent from GitHub Actions.
            Attached is the log file generated by Robot Framework.
          attachments: /home/runner/work/RF-Automation-Test/RF-Automation-Test/Admin/Test\ Cases/Reports/log.html
          attachments-disposition: attachment
