name: Run Robot Framework Tests

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  run_tests:
    name: Run Robot Framework Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python and pip
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          pip-version: latest

      - name: Install dependencies
        run: |
          pip install robotframework
          pip install robotframework-requests
          pip install robotframework-seleniumlibrary
          pip install rpaframework

      - name: Run Robot Framework tests
        run: |
          robot Admin/Test\ Cases/Scheduled\ Flow/createScheduled.robot

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: robot-framework-reports
          path: |
            /home/runner/work/RF-Automation-Test/RF-Automation-Test/output.xml
            /home/runner/work/RF-Automation-Test/RF-Automation-Test/log.html
            /home/runner/work/RF-Automation-Test/RF-Automation-Test/report.html

      - name: Send Email with log.html attachment
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          # Required server port:
          server_port: 465
          # Optional whether this connection use TLS:
          secure: true
          # Required mail server username:
          username: ${{secrets.EMAIL_USERNAME}}
          # Required mail server password:
          password: ${{secrets.EMAIL_PASSWORD}}
          # Required mail subject:
          subject: Robot Framework Test Report
          # Required recipients' addresses:
          to: nico2795@gmail.com
          # Required sender full name (address can be skipped):
          from: GitHub Actions <nico.bustamantesolis@gmail.com>
          # Optional plain body:
          body: Attached is the log file.
          # Optional attachments:
          attachments: /home/runner/work/RF-Automation-Test/RF-Automation-Test/log.html
          # Optional HTML body:
          html_body: |
            <h1>Robot Framework Test Report</h1>
            <p>This is a test report generated by GitHub Actions.</p>
