name: Run Robot Framework Tests and Send Email

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  run_tests_and_send_email:
    name: Run Robot Framework Tests and Send Email
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python and pip
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          pip-version: latest

      - name: Install dependencies
        run: |
          pip install robotframework
          pip install robotframework-requests
          pip install robotframework-seleniumlibrary
          pip install rpaframework

      - name: Run Robot Framework tests
        run: |
          robot Admin/Test\ Cases/Scheduled\ Flow/createScheduled.robot

      - name: Upload Log File
        uses: actions/upload-artifact@v2
        with:
          name: log-file
          path: /home/runner/work/RF-Automation-Test/RF-Automation-Test/log.html

      - name: Move log.html to Reports folder
        run: |
          mv /home/runner/work/RF-Automation-Test/RF-Automation-Test/log.html /home/runner/work/RF-Automation-Test/RF-Automation-Test/Admin/Test\ Cases/Reports/


