name: Run Robot Framework Tests and Send Email

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  run_tests_and_send_email:
    name: Run Robot Framework Tests and Send Email
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python and pip
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          pip-version: latest

      - name: Install dependencies
        run: |
          pip install robotframework
          pip install robotframework-requests
          pip install robotframework-seleniumlibrary
          pip install rpaframework

      - name: Run Robot Framework tests
        run: |
          robot Admin/Test\ Cases/Scheduled\ Flow/createScheduled.robot

      - name: Upload Log File Artifact
        uses: actions/upload-artifact@v2
        with:
          name: log-file
          path: /home/runner/work/RF-Automation-Test/RF-Automation-Test/log.html

      - name: Move Log File to Reports Folder
        run: |
          # Obtener la ruta del artifact generado
          artifact_path=$(curl -s https://api.github.com/repos/Nico2795/RF-Automation-Test/actions/runs/$GITHUB_RUN_ID/artifacts | jq -r '.artifacts[0].archive_download_url')

          # Descargar el artifact
          wget -qO artifact.zip $artifact_path

          # Extraer el archivo log.html del artifact
          unzip -q artifact.zip

          # Mover log.html a la carpeta deseada
          mkdir -p Admin/Test\ Cases/Reports
          mv log.html Admin/Test\ Cases/Reports/
